### ISSUE TITLE
Namespace API docs by the system name

### ISSUE THREAD

**Issue by ar-x** [ar-x/turtlecoin-wiki#12]
Folder in wiki for Walletd/TurtleCoind content: `/api/walletd-and-turtlecoind/index.md` - so this would configure its own languages tabs - shell, php, js etc. The docs would be viewable at `/walletd-and-turtlecoind/`. Maybe this would just have `walletd` docs, I'm just hypothetically speaking here.

Now if a new system comes along, which also need multiple language based API documentation. Folder in wiki for that content: `/api/some-new-system/index.md`. This could now configure its own set of language tabs. Slate would then show the docs at `/some-new-system/`. 

This would also give us a chance to build a home page at `/` which would showcase all API docs.

**Comment by ar-x** [comment]
@timmcleod let me know what you think. cc @SoreGums

**Comment by ar-x** [comment]
So in effect the 2 would end being complete isolated single page sites

**Comment by SoreGums** [comment]
i like it - then the whole thing can be wrapped in headers and footers and live wherever we need it to.

I think the important part is

> each system has its own language tabs

?

**Comment by ar-x** [comment]
To be clear, my comment above notes how the system already works today, if the content is organized into system specific folders that way.

> then the whole thing can be wrapped in headers and footers.

Do you mean, that given another system folder of API docs, would it get auto wrapped in the site layout - which includes the header, footer, system specific left sidebar.  If so, Yes.

>  and live wherever we need it to.

Without any change today, the docs would _only_ show up at `https://hinata-104.shadow-clone-jutsu.com/new-system-name/`. This is because the `gh-pages` of the api-docs-site repo is set to `hinata-104.shadow-clone-jutsu.com`. GH Pages only supports one custom domain.

If you want to 

* add the new system api docs to `/api`, and 
* have it show using the api-docs-site UI, and
* use your own custom domain

Then, we'll need to do something a little more, which is easy as well. One option here is – fork the docs site, and set up your own custom domain on that. And then add JSON file which would map  api folders to domains. I'm sure there are other ways of doing this as well.  Something for the future.


> each system has its own language tabs

Yep, thats the idea there.

**Comment by ar-x** [comment]
I've done the analysis needed for this. This can easily to done once we have a second system.

**Comment by ar-x** [comment]
in case its desired to be done now, ping me and I'll make the required code changes (yes, a bit of it is needed).
